// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXUF4qjXBCimemukc2VcckIU0HUen_Ts',
    appId: '1:379944428142:web:d169d453a8776cab19fc7f',
    messagingSenderId: '379944428142',
    projectId: 'appffn-b14d1',
    authDomain: 'appffn-b14d1.firebaseapp.com',
    storageBucket: 'appffn-b14d1.firebasestorage.app',
    measurementId: 'G-7CZ58NL1L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKqLVTuSxvkvaCS4jbHGSLkqzijIQhUc',
    appId: '1:379944428142:android:3f282fffb7ecec5319fc7f',
    messagingSenderId: '379944428142',
    projectId: 'appffn-b14d1',
    storageBucket: 'appffn-b14d1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJXUF4qjXBCimemukc2VcckIU0HUen_Ts',
    appId: '1:379944428142:web:25b7ce538d29c79e19fc7f',
    messagingSenderId: '379944428142',
    projectId: 'appffn-b14d1',
    authDomain: 'appffn-b14d1.firebaseapp.com',
    storageBucket: 'appffn-b14d1.firebasestorage.app',
    measurementId: 'G-QH8LQDHTZE',
  );
}
